### ISSUE TITLE
[BUG] game crashes when using wheel's say or command feature on a server

### ISSUE THREAD

**Issue by ttrafford7** [ClockwerkKaiser/MineMenu-Refabricated#3]
---- Minecraft Crash Report ----
// There are four lights!

Time: 2022-09-03 13:43:44
Description: mouseClicked event handler

java.lang.NoSuchMethodError: 'void net.minecraft.class_746.method_3142(java.lang.String)'
	at com.github.clockwerkkaiser.minemenufabric.client.screen.MineMenuSelectScreen.handleTypes(MineMenuSelectScreen.java:287)
	at com.github.clockwerkkaiser.minemenufabric.client.screen.MineMenuSelectScreen.method_25402(MineMenuSelectScreen.java:210)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:198)
	at net.minecraft.class_1041.method_15998(class_1041.java:453)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.clockwerkkaiser.minemenufabric.client.screen.MineMenuSelectScreen.handleTypes(MineMenuSelectScreen.java:287)
	at com.github.clockwerkkaiser.minemenufabric.client.screen.MineMenuSelectScreen.method_25402(MineMenuSelectScreen.java:210)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:198)

-- Affected screen --
Details:
	Screen name: com.github.clockwerkkaiser.minemenufabric.client.screen.MineMenuSelectScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:198)
	at net.minecraft.class_1041.method_15998(class_1041.java:453)
	at net.minecraft.class_310.method_1523(class_310.java:1205)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 12 total; [class_746['ttrafford'/4688368, l='ClientLevel', x=15.16, y=70.00, z=20.07], class_745['8jok372y17'/58, l='ClientLevel', x=-8.50, y=67.00, z=-4.50], class_745['5p7is5b5yf'/9, l='ClientLevel', x=3.50, y=68.00, z=-2.50], class_745['e613924o72'/11, l='ClientLevel', x=-0.50, y=68.00, z=-8.50], class_745['4c9813844m'/12, l='ClientLevel', x=1.50, y=68.00, z=-5.50], class_745['za92v1f3z4'/10, l='ClientLevel', x=3.50, y=68.00, z=3.50], class_745['b4d2vd5e52'/59, l='ClientLevel', x=13.50, y=69.00, z=17.50], class_745['iyo1442801'/1, l='ClientLevel', x=3.50, y=67.00, z=-14.50], class_745['1e4651q4oa'/2, l='ClientLevel', x=10.50, y=67.00, z=0.50], class_745['o1g21zw608'/3, l='ClientLevel', x=1.50, y=68.00, z=6.50], class_745['1gon9umt19'/5, l='ClientLevel', x=-0.50, y=68.00, z=9.50], class_745['1gon9umt19'/7, l='ClientLevel', x=-17.50, y=70.00, z=7.50]]
	Chunk stats: 5041, 169
	Level dimension: minecraft:overworld
	Level spawn location: World: (-25,70,0), Section: (at 7,6,0 in -2,4,0; chunk contains blocks -32,0,0 to -17,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 247044926 game time, 389000 day time
	Server brand: Hypixel BungeeCord (1.3.0) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:580)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, blocky-mushrooms-e1250.zip, Smoother Wood Blocks, Potion Particles 1.19.zip, Particles+V.1.2.2.zip, xali-s-Enchanted-Books-16x-v0.10.1.zip, vixel-s-diamonded-netherite.zip, VanillaTweaks_r942682.zip, Simple+Grass+Flowers+v1.2.1.zip

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1101303568 bytes (1050 MiB) / 1811939328 bytes (1728 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Pentium(R) 3805U @ 1.90GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: unknown
	Frequency (GHz): 1.90
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: Intel(R) HD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x1606
	Graphics card #0 versionInfo: DriverVersion=20.19.15.4835
	Graphics card #1 name: NVIDIA GeForce 820M
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x1140
	Graphics card #1 versionInfo: DriverVersion=23.21.13.8934
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Virtual memory max (MB): 9383.34
	Virtual memory used (MB): 6057.76
	Swap memory total (MB): 1280.00
	Swap memory used (MB): 81.80
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.13
		autoswitch: AutoSwitch 5.1.2
			autoswitch-api: AutoSwitch API 1.1.0
			org_aeonbits_owner_owner: owner 1.0.12
		chat_heads: Chat Heads 0.7.1
		cloth-config: Cloth Config v8 8.0.75
			cloth-basic-math: cloth-basic-math 0.6.1
		cmdkeybind: Command Macros 1.6.0-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		fabric-api: Fabric API 0.60.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.9+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.17+aeb40ebe90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.20+aeb40ebe90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.1+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.11+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.7+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.28+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.34+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.3+aeb40ebe90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.1+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.5+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.8+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.30+aeb40ebe90
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.18+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.28+aeb40ebe90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.28+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.21+aeb40ebe90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.7+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.28+aeb40ebe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.18+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.2+aeb40ebe90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.3+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.6+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.3+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.14+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.17+aeb40ebe90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.4+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.21+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.11+aeb40ebe90
			fabric-particles-v1: Fabric Particles (v1) 1.0.10+aeb40ebe90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.24+aeb40ebe90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.10+aeb40ebe90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.12+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.20+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.22+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.16+aeb40ebe90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.11+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.26+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.13+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.20+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.11+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.0+42d99c3290
		fabricloader: Fabric Loader 0.14.9
		itemscroller: Item Scroller 0.17.1
		java: OpenJDK 64-Bit Server VM 17
		malilib: MaLiLib 0.13.0
		minecraft: Minecraft 1.19.2
		minemenufabric: MineMenuFabric 6.2.1-1.19
		modmenu: Mod Menu 4.0.6
		optifabric: OptiFabric 1.13.16
			mm: Manningham Mills 2.3
		symbol-chat: Symbol Chat 0.3.2
		tweakeroo: Tweakeroo 0.14.3
		xaerominimap: Xaero's Minimap 22.13.2
		xaeroworldmap: Xaero's World Map 1.26.5
	Launched Version: fabric-loader-0.14.9-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: GeForce 820M/PCIe/SSE2 GL version 3.2.0 NVIDIA 389.34, NVIDIA Corporation
	Window size: 1366x697
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/blocky-mushrooms-e1250.zip, file/Smoother Wood Blocks, file/Potion Particles 1.19.zip, file/Particles+V.1.2.2.zip, file/xali-s-Enchanted-Books-16x-v0.10.1.zip, file/vixel-s-diamonded-netherite.zip, file/VanillaTweaks_r942682.zip, file/Simple+Grass+Flowers+v1.2.1.zip
	Current Language: English (US)
	CPU: 2x Intel(R) Pentium(R) 3805U @ 1.90GHz
	OptiFine Version: OptiFine_1.19.2_HD_U_H9
	OptiFine Build: 20220820-230904
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 389.34
	OpenGlRenderer: GeForce 820M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.19.2
	OptiFine jar version: OptiFine_1.19.2_HD_U_H9
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: D:/Minecraft Instances/Minigames/.optifine/OptiFine_1.19.2_HD_U_H9/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by ClockwerkKaiser** [comment]
1.19.2 is not yet supported. The chat report/verification system requires me to make some changes that I'm not yet fully understanding of. 

Once I have time to dive into the favric docs, I'll work on updating. 

For now, the mod is only for 1.18.2 and 1.19

**Comment by ClockwerkKaiser** [comment]
This is now fixed
